### ISSUE TITLE
Something wrong during initContainers

### ISSUE THREAD

**Issue by roychen11232357** [yogeshlonkar/pod-dependency-init-container#1]
Hi there, 

this tool is so cool, that's what I want, but when I deploy my app to k8s cluster, something wrong,

`code: 403, statusCode: 403 } pods is forbidden: User "system:serviceaccount:{{MY_NAMESPACE}}:default" cannot list resource "pods" in API group "" at the cluster scope Error: pods is forbidden: User "system:serviceaccount:{{MY_NAMESPACE}}:default" cannot list resource "pods" in API group "" at the cluster scope`

Do you know what kinds of problem causes this error, Could you help me, thanks!

**Comment by yogeshlonkar** [comment]
this seems issue with RBAC. Make sure `serviceAccountName` associated to this container has `pod` resource access
