### ISSUE TITLE
RETRY_TIME_OUT does not work?

### ISSUE THREAD

**Issue by roychen11232357** [yogeshlonkar/pod-dependency-init-container#2]
Hi there, 

I can use this project to achieve my goal now, but I found that the RETRY_TIME_OUT not woks properly?

I found than the setTimeout used hardcode 1500 of index.js, maybe this is the reason?

thanks!

**Comment by yogeshlonkar** [comment]
Thanks for reporting issue. You can use docker tag `1.0.1`
