### ISSUE TITLE
delete old versions in github

### ISSUE THREAD

**Issue by angelcos** [yogeshlonkar/pod-dependency-init-container#5]
I used the github repo "ylonkar/pod-dependency-init-container" with version 1.0 and suddenly stop working be cause the version 1.0 was no longer available. You should keep the old versions for backward compatibility.

**Comment by yogeshlonkar** [comment]
Sorry for inconvenience. I have restored 1.0 can you upgrade to 1.0.1 ? because retry time out is not working in old version
